// RootLayout Component
import { AuthProvider } from "../../contexts/AuthContext";
import { GroupProvider } from "../../contexts/GroupContext";
import { ThemeProvider } from "../../contexts/ThemeContext";
import ClientWrapper from "./ClientWrapper"

// Styles and Metadata
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "LabtecOne",
  description: "Generated by create next app",
  icons: {
    icon: "/dev/one/favicon.ico",
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `!function(){try{var t=sessionStorage.getItem('userTheme')||'${process.env.NEXT_PUBLIC_DEFAULT_THEME || ''}'||'BG_LIGHT',e=document.documentElement;'BG_DARK'===t?(e.classList.add('dark'),e.style.colorScheme='dark'):(e.classList.remove('dark'),e.style.colorScheme='light')}catch(t){}}();`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        {/* Providers */}
        <ThemeProvider>
          <AuthProvider>
            {
              // Sidebar and Group Providers
                <GroupProvider>

                  {/* Group Sidebar */}
                  <ClientWrapper>
                    {children}
                  </ClientWrapper>

                </GroupProvider>
            }
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}