// RootLayout Component
import { AuthProvider } from "../../contexts/AuthContext";
import { GroupProvider } from "../../contexts/GroupContext";
import { ThemeProvider } from "../../contexts/ThemeContext";
import ClientWrapper from "./ClientWrapper"

// Styles and Metadata
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "LabtecOne",
  description: "Generated by create next app",
  icons: {
    icon: "/dev/one/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Inline script para aplicar o tema antes da hydration (evita flash de tema).
            Prioriza `NEXT_PUBLIC_DEFAULT_THEME` quando definido no ambiente. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var envTheme='${process.env.NEXT_PUBLIC_DEFAULT_THEME || ''}';var t=envTheme||localStorage.getItem('theme');if(t==='BG_DARK'){document.documentElement.classList.add('dark');document.documentElement.style.colorScheme='dark';}else{document.documentElement.classList.remove('dark');document.documentElement.style.colorScheme='light';}}catch(e){console.error('Theme script error:',e);} })();`,
          }}
        />
        {/* Providers */}
        <ThemeProvider>
          <AuthProvider>
            {
              // Sidebar and Group Providers
                <GroupProvider>

                  {/* Group Sidebar */}
                  <ClientWrapper>
                    {children}
                  </ClientWrapper>

                </GroupProvider>
            }
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}