// RootLayout Component
import { AuthProvider } from "../../contexts/AuthContext";
import { GroupProvider } from "../../contexts/GroupContext";
import ClientWrapper from "./ClientWrapper"

// Styles and Metadata
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "LabtecOne",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Providers */}
        <AuthProvider>
          {
            // Sidebar and Group Providers
              <GroupProvider>

                {/* Group Sidebar */}
                <ClientWrapper>
                  {children}
                </ClientWrapper>

              </GroupProvider>
          }
        </AuthProvider>
      </body>
    </html>
  );
}